on: # Controls when the workflow will run
  push:
    branches:
      - master

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  
  build:
    runs-on: macOS-latest   # The type of runner that the job will run on


    steps:
      - name: Set the value
        id: step_one
        run: |
          cat build/version.properties >> $GITHUB_ENV
#      - name: Use the value
#        id: step_two
#        run: |
#          echo "${{  $GITHUB_ENV }}" # This will output 'yellow'


#    steps:
#      - name: Set the value
#        id: step_one
#        run: |
#          echo "action_state=yellow" >> $GITHUB_ENV
#      - name: Use the value
#        id: step_two
#        run: |
#          echo "${{ env.action_state }}" # This will output 'yellow'

#steps:
# - name: Read branch.properties
#        id: version
#        uses: actions/checkout@v1
#        with:
#          path: ./BuildVersion.txt

 #- name: Assign release version from BuildVersion.txt to Env variable
 #       run: |
 #          echo "${{ steps.version.outputs.content }}" >> $GITHUB_ENV          
          
 # - name: Echo release version from  Env variable
 #        run: |
 #           echo "${{ env.release_version }}"


    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      - uses: actions/checkout@v2
#      - name: Create BuildVersion.txt file
#        run: |
#          echo "${{ github.run_number }}" > BuildVersion.txt
#
#          git config --global user.name 'maurodevitopix4d'
#          git config --global user.email 'mauro.devito@pix4d.com'          
#          git add BuildVersion.txt
#          git commit -am "Version ${{ github.run_number }} added on BuildVersion.txt"
#          git push
#        shell: bash
