name: "Read file contents"

on: # Controls when the workflow will run
  push:
    branches:
      - master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read file
        id: step_a
        run: cat BuildVersion.txt >> $GITHUB_ENV

      - name: Use the value
        id: step_b
        env:  
          VER:  ${{ github.run_number }}        
        run: |
          echo $((${{ env.version }}+$VER))

