name: "Increment build number"

on: # Controls when the workflow will run
  push:
    branches:
      - master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read ConfigVersion from file
        id: step_a
        run: cat ConfigVersion.txt >> $GITHUB_ENV 

      - name: Write new version on ConfigVersion.txt
        id: step_b
        run: |
          echo "Version ${{ env.AppVersion }} - ($((${{ env.BuildVersion }}+1)))"
          echo "AppVersion=${{ env.AppVersion }}"
          echo "BuildVersion=$((${{ env.BuildVersion }}+1))"
  


#    if: ${{ env.ManualBuildVersion }} < ${{ env.AutomaticBuildVersion }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

        # ManualVersion = Last Manual_Build_Version set manually (eg: TestFlight build) and/or Initial_Offset
#      - name: Read ManualVersion from file
#        id: step_a
#        run: cat ManualVersion.txt >> $GITHUB_ENV 

#      - name: Write new version on BuildVersion.txt from last automatic
#        id: step_inc_b
#        run: |
#          echo "Version ${{ env.AppVersion }} - ($((${{ env.AutomaticBuildVersion }}+1)))"
#          echo "AppVersion=${{ env.AppVersion }}"
#          echo "AutomaticBuildVersion=$((${{ env.AutomaticBuildVersion }}+1))"
#          echo "ManualBuildVersion=${{ env.ManualBuildVersion }}"



#      - name: Write new version on BuildVersion.txt from last manual
#        id: step_inc_a
#        env:  
#          VER:  ${{ github.run_number }}        
#        run: |
#          echo "Version ${{ env.AppVersion }} - ($((${{ env.ManualBuildVersion }}+$VER)))"
#          echo "AppVersion=${{ env.AppVersion }}"
#          echo "AutomaticBuildVersion=$((${{ env.ManualBuildVersion }}+$VER))"
#          echo "ManualBuildVersion=${{ env.ManualBuildVersion }}"

#
#          
#          echo "BuildVersion=$((${{ env.version }}+$VER))"" > BuildVersion.txt 
#          git config --global user.name 'maurodevitopix4d'
#          git config --global user.email 'mauro.devito@pix4d.com'          
#          git add BuildVersion.txt
#          git commit -am "Version ${{ env.AppVersion }} - Build Number: ($((${{ env.version }}+$VER)))"
#          git push