name: "Read file contents"

on: # Controls when the workflow will run
  push:
    branches:
      - master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read file
        id: step_a
        run: cat BuildVersion.txt >> $GITHUB_ENV

      - name: Use the value
        id: step_b
        run: |
          echo "${{ env.version }}"

      - name: Use the xxx
        id: step_c
        env:  
          NUM: ${{ env.version }}
        run: |
          echo $(($NUM+200))

      - name: Use the yyy
        id: step_d
        env:  
          VER:  ${{ github.run_number }}
        run: |
          echo $((${{ env.version }}+$VER))
