name: "Read file contents"

on: # Controls when the workflow will run
  push:
    branches:
      - master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read file
        id: step_a
        run: cat BuildVersion.txt >> $GITHUB_ENV

      - name: Use the value
        id: step_b
        run: |
          echo "${{ env.version }}"

      - name: Use the xxx
        id: step_c
        env:  
          NUM: ${{ env.version }}
        run: |
          echo $(($NUM+200))

      - name: Use the yyy
        id: step_d
        env:  
          VER:  ${{ github.run_number }}
        run: |
          echo $(($VER+200))
          echo $((${{ env.version }}+$VER))


#      - name: run number with offset
#        env:
#          NUM: ${{ github.run_number }}
#        run: |
#          echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+200))
#      - run: echo $GITHUB_RUN_NUMBER_WITH_OFFSET


#      env:
#          NUM: ${{ github.run_number }}
#      run: |
#          echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+200))          

# https://github.com/marketplace/actions/file-reader

# jobs:
#   file_contents:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: maurodevito/checkout@v1

#       - name: Read file contents
#         id: read_file
#         uses: maurodevito/BuildVersion@master
#         with:
#           path: "BuildVersion.txt"

#       - name: File contents
#         run: |
#           echo "INIZIO"
#           echo "${ steps.read_file.outputs }"
#           echo "FINE"




#    steps:
#      - name: Set the value
#        id: step_one
#        run: |
#          echo "action_state=yellow" >> $GITHUB_ENV
#      - name: Use the value
#        id: step_two
#        run: |
#          echo "${{ env.action_state }}" # This will output 'yellow'

#steps:
# - name: Read branch.properties
#        id: version
#        uses: actions/checkout@v1
#        with:
#          path: ./BuildVersion.txt

 #- name: Assign release version from BuildVersion.txt to Env variable
 #       run: |
 #          echo "${{ steps.version.outputs.content }}" >> $GITHUB_ENV          
          
 # - name: Echo release version from  Env variable
 #        run: |
 #           echo "${{ env.release_version }}"


    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      - uses: actions/checkout@v2
#      - name: Create BuildVersion.txt file
#        run: |
#          echo "${{ github.run_number }}" > BuildVersion.txt
#
#          git config --global user.name 'maurodevitopix4d'
#          git config --global user.email 'mauro.devito@pix4d.com'          
#          git add BuildVersion.txt
#          git commit -am "Version ${{ github.run_number }} added on BuildVersion.txt"
#          git push
#        shell: bash
