name: "Increment build number"

on: # Controls when the workflow will run
  push:
    branches:
      - master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        # ManualVersion = Last Manual_Build_Version set manually (eg: TestFlight build) and/or Initial_Offset
      - name: Read ManualVersion from file
        id: step_a
        run: cat ManualVersion.txt >> $GITHUB_ENV 


#        # BuildVersion = the last BuildVersion automatically calculated (considering the ManualVersion off-set)
#      - name: Read BuildVersion from file
#        id: step_a
#        run: cat BuildVersion.txt >> $GITHUB_ENV 

        # BuildVersion = New BuildVersion user as Build number
      - name: Write new version on BuildVersion.txt
        id: step_b
        env:  
          VER:  ${{ github.run_number }}        
        run: |
          echo "Version ${{ env.AppVersion }} - ($((${{ env.ManualBuildVersion }}+$VER)))"
          echo "AppVersion=${{ env.AppVersion }}
 
 #
 
 #         echo "AppVersion=${{ env.AppVersion }}"
 #         echo "AutomaticBuildVersion=$((${{ env.ManualBuildVersion }}+$VER))"
          

#echo "ManualBuildVersion=${{ env.ManualBuildVersion }}""

#AppVersion=1.12.0
#AutomaticBuildVersion=20
#ManualBuildVersion=20
#
#          
#          echo "BuildVersion=$((${{ env.version }}+$VER))"" > BuildVersion.txt 
#          git config --global user.name 'maurodevitopix4d'
#          git config --global user.email 'mauro.devito@pix4d.com'          
#          git add BuildVersion.txt
#          git commit -am "Version ${{ env.AppVersion }} - Build Number: ($((${{ env.version }}+$VER)))"
#          git push